### ISSUE TITLE
Unmunch doesn't recognized words with first letter accented

### ISSUE THREAD

**Issue by sricochet** [anezih/HunspellWordForms#1]
Running Unmunch.ps1 after building creates a json file that has missing words. The word list begins in the list where the words have no accent marks at the beginning of the word. This does not occur  with accent marks later in the word.

**Comment by anezih** [comment]
Could you attach the Hunspell files you used?

**Comment by sricochet** [comment]
[Greek.zip](https://github.com/anezih/HunspellWordForms/files/14858182/Greek.zip)

**Comment by anezih** [comment]
The words with accent marks at the beginning have no rules attached to them. In the dictionary you posted only 106,110 words out of 1,684,276 contain affix rules. Since those words won't have any inflected form, they are not added to the final json file (empty check here: https://github.com/anezih/HunspellWordForms/blob/6b51a09a3508fa78abcd5d016f4dbd6289296cc3/src/WordForms.cs#L189).
